name: First Workflow

on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Hello! My first GitHub Actions workflow is running."

      - name: Show date
        run: date
